[2018-Nov-19 18:00:35][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 18:00:35][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 73, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

[2018-Nov-19 18:04:41][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 18:04:41][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 75, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

[2018-Nov-19 18:06:19][Autoplacement24in96][CRITICAL] Encountered a UnboundLocalError exception: local variable 'container' referenced before assignment
[2018-Nov-19 18:06:19][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 65, in _run
    print("input keys",input_container_nested_dict[container].keys())
UnboundLocalError: local variable 'container' referenced before assignment

[2018-Nov-19 18:06:39][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 18:06:39][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_in_96.py", line 75, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

