[2018-Nov-15 10:06:07][SpectramaxOutput][INFO] Updating step 24-31264 with data: defaultdict(<class 'dict'>, {'LP9181116-QNT': {'A4': 11.668, 'B4': 12.953, 'C4': 11.956, 'D4': 14.602, 'E4': 15.004, 'F4': 13.887, 'G4': 9.784, 'H4': 9.227, 'A5': 9.264, 'B5': 17.582, 'C5': 12.502, 'D5': 8.349, 'E5': 19.791, 'F5': 12.696, 'G5': 13.008, 'H5': 12.371, 'A6': 13.612, 'B6': 14.669, 'C6': 14.631, 'D6': 15.86, 'E6': 13.383, 'F6': 9.6, 'G6': 9.344, 'A7': 13.487, 'B7': 18.704, 'C7': 17.042, 'D7': 10.437, 'E7': 9.78, 'F7': 51.478, 'G7': 29.193, 'H7': 40.868, 'A8': 31.263, 'B8': 92.617, 'C8': 24.526, 'D8': 20.771, 'E8': 15.419, 'F8': 13.558, 'G8': 13.504, 'H8': 20.026, 'A9': 20.408, 'B9': 14.256, 'C9': 14.809, 'D9': 13.044, 'E9': 16.158, 'F9': 17.959, 'G9': 14.0, 'A10': 16.957, 'B10': 10.44, 'C10': 19.174, 'D10': 14.89, 'E10': 13.281, 'F10': 18.997, 'G10': 15.905, 'H10': 11.266, 'A11': 17.499, 'B11': 19.764, 'C11': 16.318, 'D11': 10.108, 'E11': 17.18, 'F11': 18.287, 'G11': 15.628, 'H11': 15.328, 'A12': 10.231, 'B12': 18.013, 'C12': 17.457, 'D12': 16.377, 'E12': 12.438, 'F12': 15.503, 'G12': 21.822}})
[2018-Nov-15 10:06:26][SpectramaxOutput][CRITICAL] Encountered a TypeError exception: unsupported operand type(s) for +: 'int' and 'NoneType'
[2018-Nov-15 10:06:26][SpectramaxOutput][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\parse_spectramax_seq_plate_quant.py", line 124, in _run
    self.average_replicates()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\parse_spectramax_seq_plate_quant.py", line 114, in average_replicates
    total = total + replicate
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

[2018-Nov-15 10:08:47][SpectramaxOutput][CRITICAL] Encountered a ValueError exception: could not convert string to float: 
[2018-Nov-15 10:08:47][SpectramaxOutput][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\parse_spectramax_seq_plate_quant.py", line 121, in _run
    self.parse_spectramax_file()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\parse_spectramax_seq_plate_quant.py", line 42, in parse_spectramax_file
    self.sample_concs[int(split_line[0])] = (split_line[1], float(split_line[3]))
ValueError: could not convert string to float: 

[2018-Nov-15 10:10:09][SpectramaxOutput][INFO] Updating step 24-31264 with data: defaultdict(<class 'dict'>, {'LP9181116-QNT': {'A4': 11.668, 'B4': 12.953, 'C4': 11.956, 'D4': 14.602, 'E4': 15.004, 'F4': 13.887, 'G4': 9.784, 'H4': 9.227, 'A5': 9.264, 'C5': 12.502, 'D5': 8.349, 'E5': 19.791, 'F5': 12.696, 'G5': 13.008, 'H5': 12.371, 'A6': 13.612, 'B6': 14.669, 'C6': 14.631, 'D6': 15.86, 'E6': 13.383, 'F6': 9.6, 'G6': 9.344, 'H6': 14.454, 'A7': 13.487, 'B7': 18.704, 'C7': 17.042, 'D7': 10.437, 'E7': 9.78, 'F7': 51.478, 'G7': 29.193, 'H7': 40.868, 'A8': 31.263, 'B8': 92.617, 'C8': 24.526, 'D8': 20.771, 'E8': 15.419, 'F8': 13.558, 'G8': 13.504, 'H8': 20.026, 'A9': 20.408, 'B9': 14.256, 'C9': 14.809, 'D9': 13.044, 'E9': 16.158, 'F9': 17.959, 'G9': 14.0, 'H9': 11.356, 'A10': 16.957, 'B10': 10.44, 'C10': 19.174, 'D10': 14.89, 'E10': 13.281, 'F10': 18.997, 'G10': 15.905, 'H10': 11.266, 'A11': 17.499, 'B11': 19.764, 'C11': 16.318, 'D11': 10.108, 'E11': 17.18, 'F11': 18.287, 'G11': 15.628, 'H11': 15.328, 'A12': 10.231, 'B12': 18.013, 'C12': 17.457, 'D12': 16.377, 'E12': 12.438, 'F12': 15.503, 'G12': 21.822, 'H12': 18.026, 'B5': 17.582}})
[2018-Nov-15 10:11:15][QCCheck][CRITICAL] Encountered a TypeError exception: '>=' not supported between instances of 'NoneType' and 'int'
[2018-Nov-15 10:11:15][QCCheck][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\qc_check.py", line 116, in _run
    self.process.udf.get(step_udf_name)) == True and \
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\qc_check.py", line 20, in ComparisonMethod
    return comparison_method(result, step_udf_value)
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

