[2018-Oct-12 11:46:56][AutoplacementQPCR384][CRITICAL] Encountered a NameError exception: name 'wellcounter' is not defined
[2018-Oct-12 11:46:56][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 79, in _run
    if plate_layout[wellcounter][1:] == 5:
NameError: name 'wellcounter' is not defined

[2018-Oct-12 11:47:43][AutoplacementQPCR384][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Oct-12 11:47:43][AutoplacementQPCR384][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 126, in run
    self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_qpcr_384.py", line 77, in _run
    output_placement_list.append((standards_dict[key],(output_container_list[0],plate_layout[well_counter])))
IndexError: list index out of range

