[2018-Nov-23 11:18:00][Autoplacement24IMPGX][CRITICAL] Encountered a AttributeError exception: 'set' object has no attribute 'append'
[2018-Nov-23 11:18:00][Autoplacement24IMPGX][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_imp_gx.py", line 32, in _run
    input_containers.append(art.container)
AttributeError: 'set' object has no attribute 'append'

[2018-Nov-23 11:20:19][Autoplacement24IMPGX][CRITICAL] Encountered a TypeError exception: You need to provide an <class 'pyclarity_lims.entities.Container'> not <class 'list'>
[2018-Nov-23 11:20:19][Autoplacement24IMPGX][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_imp_gx.py", line 45, in _run
    self.process.step.placements.selected_containers.append(container_384)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 496, in append
    self._additem(item)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 507, in _additem
    node = self._create_new_node(value)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 634, in _create_new_node
    raise TypeError('You need to provide an %s not %s' % (self.klass, type(value)))
TypeError: You need to provide an <class 'pyclarity_lims.entities.Container'> not <class 'list'>

[2018-Nov-23 11:20:45][Autoplacement24IMPGX][CRITICAL] Encountered a TypeError exception: 'Container' object does not support indexing
[2018-Nov-23 11:20:45][Autoplacement24IMPGX][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_imp_gx.py", line 92, in _run
    (container_96[0], plate96_layout[well_counter])))
TypeError: 'Container' object does not support indexing

[2018-Nov-23 11:21:47][Autoplacement24IMPGX][CRITICAL] Encountered a TypeError exception: You need to provide an <class 'pyclarity_lims.entities.Container'> not <class 'list'>
[2018-Nov-23 11:21:47][Autoplacement24IMPGX][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_imp_gx.py", line 45, in _run
    self.process.step.placements.selected_containers.append(container_384)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 496, in append
    self._additem(item)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 507, in _additem
    node = self._create_new_node(value)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\descriptors.py", line 634, in _create_new_node
    raise TypeError('You need to provide an %s not %s' % (self.klass, type(value)))
TypeError: You need to provide an <class 'pyclarity_lims.entities.Container'> not <class 'list'>

[2018-Nov-23 11:24:02][Autoplacement24IMPGX][CRITICAL] Encountered a TypeError exception: 'Container' object does not support indexing
[2018-Nov-23 11:24:02][Autoplacement24IMPGX][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_imp_gx.py", line 92, in _run
    (container_96[0], plate96_layout[well_counter])))
TypeError: 'Container' object does not support indexing

[2018-Nov-23 11:25:30][Autoplacement24IMPGX][CRITICAL] Encountered a HTTPError exception: 400: The request contains duplicate artifacts: [2-175138, 2-175139, 2-175136, 2-175137, 2-175205, 2-175206, 2-175207, 2-175208, 2-175209, 2-175140, 2-175141, 2-175142, 2-175143, 2-175144, 2-175145, 2-175146, 2-175147, 2-175148, 2-175149, 2-175150, 2-175201, 2-175202, 2-175203, 2-175204]
[2018-Nov-23 11:25:30][Autoplacement24IMPGX][ERROR] Stack trace below:
Traceback (most recent call last):
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "C:\Users\dforth\PycharmProjects\clarity_scripts\scripts\autoplacement_24_imp_gx.py", line 102, in _run
    self.process.step.set_placements(output_containers, output_placement_list)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 946, in set_placements
    self.placements.root = self.placements.post()
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\entities.py", line 96, in post
    return self.lims.post(self.uri, data)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 166, in post
    return self.parse_response(r, accept_status_codes=[200, 201, 202])
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 209, in parse_response
    self.validate_response(response, accept_status_codes)
  File "C:\Users\dforth\PycharmProjects\untitled\venv\lib\site-packages\pyclarity_lims\lims.py", line 202, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: The request contains duplicate artifacts: [2-175138, 2-175139, 2-175136, 2-175137, 2-175205, 2-175206, 2-175207, 2-175208, 2-175209, 2-175140, 2-175141, 2-175142, 2-175143, 2-175144, 2-175145, 2-175146, 2-175147, 2-175148, 2-175149, 2-175150, 2-175201, 2-175202, 2-175203, 2-175204]

